name       : fcitx-libpinyin
version    : 0.5.4
release    : 2
source     :
    - https://github.com/fcitx/fcitx-libpinyin/archive/refs/tags/0.5.4.tar.gz : af230d530da552fee46d4d8ebe6e0d7c5085dd1c04e72b3e98691f6219fa2a7c
    - https://download.fcitx-im.org/data/model.text.20161206.tar.gz : 5c7024e5735389c471f54b867eda0d98c5a40a5e5e75333a9febac107508f704
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Chinese input method based on libpinyin for fcitx
description: |
    Chinese input method based on libpinyin for fcitx
builddeps  :
    - pkgconfig(libpinyin)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - fcitx-qt5-devel
setup      : |
    cp $sources/model.text.20161206.tar.gz $workdir/data/
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
